In [1]:
import pandas as pd
import numpy as np

In [2]:
malicious_files = ["bruteforce.csv", "capture_flood.csv", "capture_malariaDoS.csv", "malformed.csv", "mqtt_bruteforce.csv", "slowrite.csv"]
benign_files = ["capture_1w.csv", "normal.csv"]

In [3]:
def filter(df):
    df.replace({True:1,False:0}, inplace=True)
    return df

In [4]:
df = pd.read_csv("capture_1w.csv")
filter(df)
df['output'] = 0
print(df.head())

   packet_len  ip_len  ip_df  ip_mf  ip_ttl  tcp_len  tcp_pdu_size  tcp_ack  \
0          76      60      1      0      64       40            10        0
1          76      60      1      0      64       40            10        1
2          68      52      1      0      64       32             8        1
3          76      60      1      0      64       40            10        0
4          76      60      1      0      64       40            10        1

   tcp_cwr  tcp_ece  ...  tcp_urg  tcp_src_port  tcp_dst_port  tcp_tdelta  \
0        0        0  ...        0         39937          1883           0
1        0        0  ...        0          1883         39937          12
2        0        0  ...        0         39937          1883          10
3        0        0  ...        0         38969          1883        8652
4        0        0  ...        0          1883         38969          11

   tcp_l20_avg  mqtt_len  mqtt_topic_len  mqtt_msg_type  mqtt_qos_lvl  output
0            0         0               0              0             0       0
1            6         0               0              0             0       0
2            9         0               0              0             0       0
3         2172         0               0              0             0       0
4         2174         0               0              0             0       0

[5 rows x 25 columns]

In [5]:
df = pd.read_csv("normal.csv")
filter(df)
df['output'] = 0
print(df.head())

   packet_len  ip_len  ip_df  ip_mf  ip_ttl  tcp_len  tcp_pdu_size  tcp_ack  \
0          74      60      1      0      64       40            10        0
1          74      60      1      0      63       40            10        1
2          66      52      1      0      64       32             8        1
3         115     101      1      0      64       32             8        1
4          66      52      1      0      63       32             8        1

   tcp_cwr  tcp_ece  ...  tcp_urg  tcp_src_port  tcp_dst_port  tcp_tdelta  \
0        0        0  ...        0         56572          1883           0
1        0        0  ...        0          1883         56572         443
2        0        0  ...        0         56572          1883         225
3        0        0  ...        0         56572          1883          81
4        0        0  ...        0          1883         56572         126

   tcp_l20_avg  mqtt_len  mqtt_topic_len  mqtt_msg_type  mqtt_qos_lvl  output
0            0         0               0              0             0       0
1          221         0               0              0             0       0
2          296         0               0              0             0       0
3          316         0               0              0             0       0
4          341         0               0              0             0       0

[5 rows x 25 columns]

In [6]:
for name in malicious_files:
    df1 = pd.read_csv(name);
    filter(df1)
    df1['output'] = 1
    df = pd.concat([df, df1], ignore_index=True)

In [7]:
df.head()

,packet_len,ip_len,ip_df,ip_mf,ip_ttl,tcp_len,tcp_pdu_size,tcp_ack,tcp_cwr,tcp_ece,...,tcp_urg,tcp_src_port,tcp_dst_port,tcp_tdelta,tcp_l20_avg,mqtt_len,mqtt_topic_len,mqtt_msg_type,mqtt_qos_lvl,output
0,74,60,1,0,64,40,10,0,0,0,...,0,56572,1883,0,0,0,0,0,0,0
1,74,60,1,0,63,40,10,1,0,0,...,0,1883,56572,443,221,0,0,0,0,0
2,66,52,1,0,64,32,8,1,0,0,...,0,56572,1883,225,296,0,0,0,0,0
3,115,101,1,0,64,32,8,1,0,0,...,0,56572,1883,81,316,0,0,0,0,0
4,66,52,1,0,63,32,8,1,0,0,...,0,1883,56572,126,341,0,0,0,0,0

In [8]:
shuffled = df.sample(frac=1, random_state=1).reset_index()
shuffled.head()

,index,packet_len,ip_len,ip_df,ip_mf,ip_ttl,tcp_len,tcp_pdu_size,tcp_ack,tcp_cwr,...,tcp_urg,tcp_src_port,tcp_dst_port,tcp_tdelta,tcp_l20_avg,mqtt_len,mqtt_topic_len,mqtt_msg_type,mqtt_qos_lvl,output
0,5380348,66,52,1,0,63,32,8,1,0,...,0,1883,35821,134,31,0,0,0,0,1
1,397915,66,52,1,0,64,32,8,1,0,...,0,35042,1883,30,-1216,0,0,0,0,0
2,11873128,66,52,1,0,64,32,8,1,0,...,0,44715,1883,45,0,0,0,0,0,1
3,2222605,66,52,1,0,64,32,8,1,0,...,0,52961,1883,53,1,0,0,0,0,1
4,11898510,66,52,1,0,64,32,8,1,0,...,0,59159,1883,64,0,0,0,0,0,1

In [9]:
df.output.unique()

array([0, 1])

In [10]:
shuffled.to_csv("all.csv",index=False)